---
- name: Install required packages
  yum: 
    name={{ item }}
    state=present
  with_items:
    - gcc-c++
    - make
    - epel-release

- name: Preparation for installing nodejs
  shell: 
    creates=/etc/yum.repos.d/nodesource-el.repo
    curl -sL https://rpm.nodesource.com/setup_4.x | bash -

- name: Install nodejs
  yum: 
    name={{ item }}
    state=present
  with_items:
    - nodejs

